imports:
    - { resource: services_acp.yml }
    - { resource: services_controller.yml }
    - { resource: services_classes.yml }
    - { resource: services_helpers.yml }
    - { resource: services_mcp.yml }
    - { resource: services_notifications.yml }
    - { resource: services_ucp.yml }

services:
    oxpus.dlext.listener:
        class: oxpus\dlext\event\listener
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
            - '@ext.manager'
            - '@path_helper'
            - '@service_container'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_privacy'
        tags:
            - { name: event.listener }
