services:
    oxpus.dlext.social:
        class: oxpus\dlext\controller\social
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_email'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_status'
