services:
    oxpus.dlext.mcp_approve:
        class: oxpus\dlext\controller\mcp\mcp_approve
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_topic'
    oxpus.dlext.mcp_broken:
        class: oxpus\dlext\controller\mcp\mcp_broken
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_topic'
    oxpus.dlext.mcp_capprove:
        class: oxpus\dlext\controller\mcp\mcp_capprove
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_main'
    oxpus.dlext.mcp_edit:
        class: oxpus\dlext\controller\mcp\mcp_edit
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_extra'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_init'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_physical'
            - '@oxpus.dlext.dlext_topic'
    oxpus.dlext.mcp_manage:
        class: oxpus\dlext\controller\mcp\mcp_manage
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_counter'
            - '@oxpus.dlext.dlext_extra'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_topic'
            - '@oxpus.dlext.dlext_status'
