services:
    oxpus.dlext.ajax:
        class: oxpus\dlext\controller\ajax
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@config'
            - '@language'
            - '@template'
            - '@request'
            - '@service_container'
    oxpus.dlext.broken:
        class: oxpus\dlext\controller\broken
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.details:
        class: oxpus\dlext\controller\details
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.fav:
        class: oxpus\dlext\controller\fav
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_main'
    oxpus.dlext.feed:
        class: oxpus\dlext\controller\feed
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@template'
            - '@user'
            - '@request'
            - '@language'
            - '@ext.manager'
            - '@service_container'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.hacklist:
        class: oxpus\dlext\controller\hacklist
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@request'
            - '@config'
            - '@language'
            - '@template'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@controller.helper'
            - '@auth'
            - '@user'
            - '@dbal.conn'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_hacklist'
            - '@oxpus.dlext.dlext_main'
    oxpus.dlext.help:
        class: oxpus\dlext\controller\help
        arguments:
            - '@language'
            - '@template'
            - '@request'
    oxpus.dlext.index:
        class: oxpus\dlext\controller\index
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_physical'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.latest:
        class: oxpus\dlext\controller\latest
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.load:
        class: oxpus\dlext\controller\load
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_init'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_physical'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.overall:
        class: oxpus\dlext\controller\overall
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.search:
        class: oxpus\dlext\controller\search
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_extra'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.stats:
        class: oxpus\dlext\controller\stats
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_main'
    oxpus.dlext.thumbs:
        class: oxpus\dlext\controller\thumbs
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_status'
    oxpus.dlext.todo:
        class: oxpus\dlext\controller\todo
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_extra'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_main'
    oxpus.dlext.tracker:
        class: oxpus\dlext\controller\tracker
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_main'
    oxpus.dlext.unbroken:
        class: oxpus\dlext\controller\unbroken
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_main'
    oxpus.dlext.unfav:
        class: oxpus\dlext\controller\unfav
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_main'
    oxpus.dlext.upload:
        class: oxpus\dlext\controller\upload
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_extra'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_init'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_physical'
            - '@oxpus.dlext.dlext_topic'
    oxpus.dlext.version:
        class: oxpus\dlext\controller\version
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_physical'
            - '@oxpus.dlext.dlext_status'
