services:
    oxpus.dlext.constants:
        class: oxpus\dlext\phpbb\helpers\constants
        public: true
        arguments:
            - '@service_container'
            - '%core.root_path%'
            - '%core.table_prefix%'
            - '@config'
            - '@user'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@oxpus.dlext.dlext_physical'
    oxpus.dlext.footer:
        class: oxpus\dlext\phpbb\helpers\footer
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
            - '@template'
            - '@controller.helper'
            - '@config'
            - '@auth'
            - '@user'
            - '@dbal.conn'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_counter'
            - '@oxpus.dlext.dlext_extra'
            - '@oxpus.dlext.dlext_files'
            - '@oxpus.dlext.dlext_format'
            - '@oxpus.dlext.dlext_init'
            - '@oxpus.dlext.dlext_main'
            - '@oxpus.dlext.dlext_physical'
    oxpus.dlext.navigation:
        class: oxpus\dlext\phpbb\helpers\navigation
        public: true
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
            - '@template'
            - '@controller.helper'
            - '@user'
            - '@service_container'
            - '@dbal.conn'
            - '@oxpus.dlext.dlext_auth'
            - '@oxpus.dlext.dlext_nav'
